Algoritmo "glicose"



Var

          glicose : real

Inicio


          escreva("Digite a medida da glicose: ")
          leia(glicose)
          
          se glicose <= 100 entao
            escreval("normal")
          senao
          se glicose <= 140 entao
            escreval("elevado")
          senao
          se glicose > 140 entao
             escreval("Diabetes")
              fimse
            fimse
          fimse
          




Fimalgoritmo